services:
  postgres:
    container_name: postgres_container
    image: postgres:latest
    environment:
      - POSTGRES_DB=async_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    restart: always

  rabbitmq:
    container_name: rabbitmq_container
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
