spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/async_db
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database: postgresql

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

  cloud:
    stream:
      function:
        definition: appCreatedEventListener;appUpdatedEventListener;
      bindings:
        HealthCheckTaskCommand-out-0:
          destination: health-check.v1.command.execute-task
        appCreatedEventListener-in-0:
          destination: app.v1.event.app-created
          group: scheduler
        appUpdatedEventListener-in-0:
          destination: app.v1.event.app-updated
          group: scheduler
        rabbit:
          bindings:
            appCreatedEventListener-in-0:
              consumer:
                auto-bind-dlq: true
            appUpdatedEventListener-in-0:
              consumer:
                auto-bind-dlq: true

server:
  port: 8083