spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/async_db
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database: postgresql

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

  cloud:
    stream:
      function:
        definition: appCreatedSupplier;appUpdatedSupplier
      bindings:
        appCreatedSupplier-out-0:
          destination: app.v1.event.app-created
        appUpdatedSupplier-out-0:
          destination: app.v1.event.app-updated

server:
  port: 8083